// <auto-generated />
using System;
using BachCrud.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BachCrud.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240405123418_trials1Db")]
    partial class trials1Db
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            CourseId = 1,
                            Email = "mohamedzekaria@uia.no",
                            FirstName = "knaan",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            CourseId = 2,
                            Email = "moham@uia.no",
                            FirstName = "zeka",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            CourseId = 3,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            CourseId = 2,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            CourseId = 3,
                            Email = "alix1@uia.no",
                            FirstName = "Alix",
                            LastName = "Calvin",
                            PhoneNumber = "4867971",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Age = 43,
                            CourseId = 3,
                            Email = "baxster2@uia.no",
                            FirstName = "Baxster",
                            LastName = "Thomas",
                            PhoneNumber = "4867972",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Age = 26,
                            CourseId = 1,
                            Email = "jenson3@uia.no",
                            FirstName = "Jenson",
                            LastName = "Burma",
                            PhoneNumber = "4867973",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Age = 23,
                            CourseId = 2,
                            Email = "reamer4@uia.no",
                            FirstName = "Reamer",
                            LastName = "Aaron",
                            PhoneNumber = "4867974",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Age = 37,
                            CourseId = 1,
                            Email = "davis5@uia.no",
                            FirstName = "Davis",
                            LastName = "Calvin",
                            PhoneNumber = "4867975",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Age = 43,
                            CourseId = 1,
                            Email = "weinstein6@uia.no",
                            FirstName = "Weinstein",
                            LastName = "Burt",
                            PhoneNumber = "4867976",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Age = 22,
                            CourseId = 1,
                            Email = "pettigrew7@uia.no",
                            FirstName = "Pettigrew",
                            LastName = "Caitlin",
                            PhoneNumber = "4867977",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Age = 19,
                            CourseId = 2,
                            Email = "allyson8@uia.no",
                            FirstName = "Allyson",
                            LastName = "Thomas",
                            PhoneNumber = "4867978",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Age = 26,
                            CourseId = 1,
                            Email = "norquist9@uia.no",
                            FirstName = "Norquist",
                            LastName = "Buster",
                            PhoneNumber = "4867979",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Age = 21,
                            CourseId = 1,
                            Email = "moore10@uia.no",
                            FirstName = "Moore",
                            LastName = "Paul",
                            PhoneNumber = "48679710",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Age = 36,
                            CourseId = 3,
                            Email = "tapia11@uia.no",
                            FirstName = "Tapia",
                            LastName = "Ike",
                            PhoneNumber = "48679711",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Age = 28,
                            CourseId = 3,
                            Email = "martin12@uia.no",
                            FirstName = "Martin",
                            LastName = "Calista",
                            PhoneNumber = "48679712",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Age = 24,
                            CourseId = 1,
                            Email = "ebner13@uia.no",
                            FirstName = "Ebner",
                            LastName = "Roger",
                            PhoneNumber = "48679713",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Age = 35,
                            CourseId = 3,
                            Email = "vail14@uia.no",
                            FirstName = "Vail",
                            LastName = "Burt",
                            PhoneNumber = "48679714",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Age = 33,
                            CourseId = 2,
                            Email = "myers15@uia.no",
                            FirstName = "Myers",
                            LastName = "Carl",
                            PhoneNumber = "48679715",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 20,
                            Age = 32,
                            CourseId = 2,
                            Email = "weinstein16@uia.no",
                            FirstName = "Weinstein",
                            LastName = "Ben",
                            PhoneNumber = "48679716",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 21,
                            Age = 19,
                            CourseId = 3,
                            Email = "tiernan17@uia.no",
                            FirstName = "Tiernan",
                            LastName = "Ben",
                            PhoneNumber = "48679717",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 22,
                            Age = 43,
                            CourseId = 3,
                            Email = "deitz18@uia.no",
                            FirstName = "Deitz",
                            LastName = "Steve",
                            PhoneNumber = "48679718",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 23,
                            Age = 34,
                            CourseId = 3,
                            Email = "mccormack19@uia.no",
                            FirstName = "McCormack",
                            LastName = "Frank",
                            PhoneNumber = "48679719",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 24,
                            Age = 40,
                            CourseId = 1,
                            Email = "tiernan20@uia.no",
                            FirstName = "Tiernan",
                            LastName = "Callie",
                            PhoneNumber = "48679720",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 25,
                            Age = 24,
                            CourseId = 3,
                            Email = "kaskel21@uia.no",
                            FirstName = "Kaskel",
                            LastName = "Joe",
                            PhoneNumber = "48679721",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 26,
                            Age = 21,
                            CourseId = 1,
                            Email = "sweeney22@uia.no",
                            FirstName = "Sweeney",
                            LastName = "Walter",
                            PhoneNumber = "48679722",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 27,
                            Age = 30,
                            CourseId = 2,
                            Email = "bauer23@uia.no",
                            FirstName = "Bauer",
                            LastName = "Carl",
                            PhoneNumber = "48679723",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 28,
                            Age = 29,
                            CourseId = 1,
                            Email = "alisain24@uia.no",
                            FirstName = "Alisain",
                            LastName = "George",
                            PhoneNumber = "48679724",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 29,
                            Age = 32,
                            CourseId = 1,
                            Email = "alisia25@uia.no",
                            FirstName = "Alisia",
                            LastName = "Burt",
                            PhoneNumber = "48679725",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 30,
                            Age = 30,
                            CourseId = 1,
                            Email = "bauer26@uia.no",
                            FirstName = "Bauer",
                            LastName = "Calandra",
                            PhoneNumber = "48679726",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 31,
                            Age = 28,
                            CourseId = 2,
                            Email = "deitz27@uia.no",
                            FirstName = "Deitz",
                            LastName = "Burl",
                            PhoneNumber = "48679727",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 32,
                            Age = 40,
                            CourseId = 3,
                            Email = "keller28@uia.no",
                            FirstName = "Keller",
                            LastName = "Calista",
                            PhoneNumber = "48679728",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 33,
                            Age = 31,
                            CourseId = 3,
                            Email = "roberts29@uia.no",
                            FirstName = "Roberts",
                            LastName = "Camellia",
                            PhoneNumber = "48679729",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 34,
                            Age = 35,
                            CourseId = 3,
                            Email = "chambers30@uia.no",
                            FirstName = "Chambers",
                            LastName = "Hal",
                            PhoneNumber = "48679730",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 35,
                            Age = 18,
                            CourseId = 1,
                            Email = "keller31@uia.no",
                            FirstName = "Keller",
                            LastName = "Calandra",
                            PhoneNumber = "48679731",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 36,
                            Age = 36,
                            CourseId = 2,
                            Email = "turco32@uia.no",
                            FirstName = "Turco",
                            LastName = "Fred",
                            PhoneNumber = "48679732",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 37,
                            Age = 29,
                            CourseId = 1,
                            Email = "jones33@uia.no",
                            FirstName = "Jones",
                            LastName = "Camelia",
                            PhoneNumber = "48679733",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 38,
                            Age = 38,
                            CourseId = 1,
                            Email = "allyson34@uia.no",
                            FirstName = "Allyson",
                            LastName = "David",
                            PhoneNumber = "48679734",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 39,
                            Age = 18,
                            CourseId = 1,
                            Email = "ferry35@uia.no",
                            FirstName = "Ferry",
                            LastName = "Otto",
                            PhoneNumber = "48679735",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 40,
                            Age = 32,
                            CourseId = 1,
                            Email = "schwager36@uia.no",
                            FirstName = "Schwager",
                            LastName = "Edward",
                            PhoneNumber = "48679736",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 41,
                            Age = 30,
                            CourseId = 2,
                            Email = "dugan37@uia.no",
                            FirstName = "Dugan",
                            LastName = "Monte",
                            PhoneNumber = "48679737",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 42,
                            Age = 37,
                            CourseId = 2,
                            Email = "rogers38@uia.no",
                            FirstName = "Rogers",
                            LastName = "Ike",
                            PhoneNumber = "48679738",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 43,
                            Age = 19,
                            CourseId = 1,
                            Email = "trussel39@uia.no",
                            FirstName = "Trussel",
                            LastName = "Burl",
                            PhoneNumber = "48679739",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 44,
                            Age = 29,
                            CourseId = 2,
                            Email = "johnsen40@uia.no",
                            FirstName = "Johnsen",
                            LastName = "Caitlyn",
                            PhoneNumber = "48679740",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 45,
                            Age = 30,
                            CourseId = 2,
                            Email = "lulloff41@uia.no",
                            FirstName = "Lulloff",
                            LastName = "Fred",
                            PhoneNumber = "48679741",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 46,
                            Age = 31,
                            CourseId = 2,
                            Email = "jenson42@uia.no",
                            FirstName = "Jenson",
                            LastName = "Bula",
                            PhoneNumber = "48679742",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 47,
                            Age = 19,
                            CourseId = 2,
                            Email = "sweeney43@uia.no",
                            FirstName = "Sweeney",
                            LastName = "Monte",
                            PhoneNumber = "48679743",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 48,
                            Age = 34,
                            CourseId = 2,
                            Email = "trebil44@uia.no",
                            FirstName = "Trebil",
                            LastName = "Matthew",
                            PhoneNumber = "48679744",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 49,
                            Age = 30,
                            CourseId = 3,
                            Email = "keller45@uia.no",
                            FirstName = "Keller",
                            LastName = "Roger",
                            PhoneNumber = "48679745",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 50,
                            Age = 18,
                            CourseId = 2,
                            Email = "schuster46@uia.no",
                            FirstName = "Schuster",
                            LastName = "Camelia",
                            PhoneNumber = "48679746",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 51,
                            Age = 34,
                            CourseId = 2,
                            Email = "allyson47@uia.no",
                            FirstName = "Allyson",
                            LastName = "Steve",
                            PhoneNumber = "48679747",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 52,
                            Age = 27,
                            CourseId = 2,
                            Email = "sawyer48@uia.no",
                            FirstName = "Sawyer",
                            LastName = "David",
                            PhoneNumber = "48679748",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 53,
                            Age = 29,
                            CourseId = 3,
                            Email = "trussel49@uia.no",
                            FirstName = "Trussel",
                            LastName = "George",
                            PhoneNumber = "48679749",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 54,
                            Age = 32,
                            CourseId = 2,
                            Email = "moore50@uia.no",
                            FirstName = "Moore",
                            LastName = "David",
                            PhoneNumber = "48679750",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 55,
                            Age = 37,
                            CourseId = 1,
                            Email = "paiser51@uia.no",
                            FirstName = "Paiser",
                            LastName = "Edward",
                            PhoneNumber = "48679751",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 56,
                            Age = 21,
                            CourseId = 2,
                            Email = "miller52@uia.no",
                            FirstName = "Miller",
                            LastName = "Buster",
                            PhoneNumber = "48679752",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 57,
                            Age = 22,
                            CourseId = 1,
                            Email = "bongard53@uia.no",
                            FirstName = "Bongard",
                            LastName = "Burl",
                            PhoneNumber = "48679753",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 58,
                            Age = 19,
                            CourseId = 2,
                            Email = "eastman54@uia.no",
                            FirstName = "Eastman",
                            LastName = "Mark",
                            PhoneNumber = "48679754",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 59,
                            Age = 21,
                            CourseId = 1,
                            Email = "tapia55@uia.no",
                            FirstName = "Tapia",
                            LastName = "Burton",
                            PhoneNumber = "48679755",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 60,
                            Age = 39,
                            CourseId = 2,
                            Email = "stahl56@uia.no",
                            FirstName = "Stahl",
                            LastName = "Calvin",
                            PhoneNumber = "48679756",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 61,
                            Age = 19,
                            CourseId = 3,
                            Email = "aikin57@uia.no",
                            FirstName = "Aikin",
                            LastName = "Aaron",
                            PhoneNumber = "48679757",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 62,
                            Age = 34,
                            CourseId = 3,
                            Email = "maki58@uia.no",
                            FirstName = "Maki",
                            LastName = "Bulah",
                            PhoneNumber = "48679758",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 63,
                            Age = 30,
                            CourseId = 3,
                            Email = "reyes59@uia.no",
                            FirstName = "Reyes",
                            LastName = "Joe",
                            PhoneNumber = "48679759",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 64,
                            Age = 24,
                            CourseId = 1,
                            Email = "shaffer60@uia.no",
                            FirstName = "Shaffer",
                            LastName = "Otto",
                            PhoneNumber = "48679760",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 65,
                            Age = 43,
                            CourseId = 3,
                            Email = "lewis61@uia.no",
                            FirstName = "Lewis",
                            LastName = "John",
                            PhoneNumber = "48679761",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 66,
                            Age = 35,
                            CourseId = 3,
                            Email = "moody62@uia.no",
                            FirstName = "Moody",
                            LastName = "David",
                            PhoneNumber = "48679762",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 67,
                            Age = 25,
                            CourseId = 1,
                            Email = "alisia63@uia.no",
                            FirstName = "Alisia",
                            LastName = "Roger",
                            PhoneNumber = "48679763",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 68,
                            Age = 31,
                            CourseId = 3,
                            Email = "schickowski64@uia.no",
                            FirstName = "Schickowski",
                            LastName = "Bulah",
                            PhoneNumber = "48679764",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 69,
                            Age = 36,
                            CourseId = 2,
                            Email = "reyes65@uia.no",
                            FirstName = "Reyes",
                            LastName = "John",
                            PhoneNumber = "48679765",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 70,
                            Age = 32,
                            CourseId = 3,
                            Email = "doran66@uia.no",
                            FirstName = "Doran",
                            LastName = "Byron",
                            PhoneNumber = "48679766",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 71,
                            Age = 42,
                            CourseId = 3,
                            Email = "nuttle67@uia.no",
                            FirstName = "Nuttle",
                            LastName = "Mark",
                            PhoneNumber = "48679767",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 72,
                            Age = 44,
                            CourseId = 2,
                            Email = "ramachandran68@uia.no",
                            FirstName = "Ramachandran",
                            LastName = "Tim",
                            PhoneNumber = "48679768",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 73,
                            Age = 42,
                            CourseId = 3,
                            Email = "bowers69@uia.no",
                            FirstName = "Bowers",
                            LastName = "Ben",
                            PhoneNumber = "48679769",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 74,
                            Age = 22,
                            CourseId = 3,
                            Email = "yates70@uia.no",
                            FirstName = "Yates",
                            LastName = "Calvin",
                            PhoneNumber = "48679770",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 75,
                            Age = 41,
                            CourseId = 1,
                            Email = "fletcher71@uia.no",
                            FirstName = "Fletcher",
                            LastName = "Bulah",
                            PhoneNumber = "48679771",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 76,
                            Age = 26,
                            CourseId = 1,
                            Email = "quinn72@uia.no",
                            FirstName = "Quinn",
                            LastName = "Bula",
                            PhoneNumber = "48679772",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 77,
                            Age = 40,
                            CourseId = 3,
                            Email = "mccormack73@uia.no",
                            FirstName = "McCormack",
                            LastName = "Ben",
                            PhoneNumber = "48679773",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 78,
                            Age = 34,
                            CourseId = 2,
                            Email = "pak74@uia.no",
                            FirstName = "Pak",
                            LastName = "Victor",
                            PhoneNumber = "48679774",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 79,
                            Age = 44,
                            CourseId = 3,
                            Email = "maki75@uia.no",
                            FirstName = "Maki",
                            LastName = "Buster",
                            PhoneNumber = "48679775",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 80,
                            Age = 35,
                            CourseId = 3,
                            Email = "norquist76@uia.no",
                            FirstName = "Norquist",
                            LastName = "Caitlin",
                            PhoneNumber = "48679776",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 81,
                            Age = 39,
                            CourseId = 2,
                            Email = "zeller77@uia.no",
                            FirstName = "Zeller",
                            LastName = "Joe",
                            PhoneNumber = "48679777",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 82,
                            Age = 32,
                            CourseId = 3,
                            Email = "sandstrom78@uia.no",
                            FirstName = "Sandstrom",
                            LastName = "Burl",
                            PhoneNumber = "48679778",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 83,
                            Age = 21,
                            CourseId = 3,
                            Email = "shaffer79@uia.no",
                            FirstName = "Shaffer",
                            LastName = "Frank",
                            PhoneNumber = "48679779",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 84,
                            Age = 38,
                            CourseId = 3,
                            Email = "weiss80@uia.no",
                            FirstName = "Weiss",
                            LastName = "Joe",
                            PhoneNumber = "48679780",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 85,
                            Age = 38,
                            CourseId = 1,
                            Email = "hesch81@uia.no",
                            FirstName = "Hesch",
                            LastName = "Calista",
                            PhoneNumber = "48679781",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 86,
                            Age = 22,
                            CourseId = 1,
                            Email = "ventotla82@uia.no",
                            FirstName = "Ventotla",
                            LastName = "Caitlin",
                            PhoneNumber = "48679782",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 87,
                            Age = 28,
                            CourseId = 3,
                            Email = "ferro83@uia.no",
                            FirstName = "Ferro",
                            LastName = "Edward",
                            PhoneNumber = "48679783",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 88,
                            Age = 43,
                            CourseId = 2,
                            Email = "ventotla84@uia.no",
                            FirstName = "Ventotla",
                            LastName = "Burt",
                            PhoneNumber = "48679784",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 89,
                            Age = 31,
                            CourseId = 3,
                            Email = "boyd85@uia.no",
                            FirstName = "Boyd",
                            LastName = "Calvin",
                            PhoneNumber = "48679785",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 90,
                            Age = 38,
                            CourseId = 1,
                            Email = "nugent86@uia.no",
                            FirstName = "Nugent",
                            LastName = "Mark",
                            PhoneNumber = "48679786",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 91,
                            Age = 28,
                            CourseId = 2,
                            Email = "moore87@uia.no",
                            FirstName = "Moore",
                            LastName = "Caitlin",
                            PhoneNumber = "48679787",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 92,
                            Age = 25,
                            CourseId = 2,
                            Email = "aikin88@uia.no",
                            FirstName = "Aikin",
                            LastName = "Callie",
                            PhoneNumber = "48679788",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 93,
                            Age = 18,
                            CourseId = 2,
                            Email = "schuster89@uia.no",
                            FirstName = "Schuster",
                            LastName = "Ben",
                            PhoneNumber = "48679789",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 94,
                            Age = 24,
                            CourseId = 2,
                            Email = "nugent90@uia.no",
                            FirstName = "Nugent",
                            LastName = "Calandra",
                            PhoneNumber = "48679790",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 95,
                            Age = 22,
                            CourseId = 1,
                            Email = "dewalt91@uia.no",
                            FirstName = "Dewalt",
                            LastName = "Calvin",
                            PhoneNumber = "48679791",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 96,
                            Age = 40,
                            CourseId = 3,
                            Email = "alix92@uia.no",
                            FirstName = "Alix",
                            LastName = "Callie",
                            PhoneNumber = "48679792",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 97,
                            Age = 40,
                            CourseId = 3,
                            Email = "quinn93@uia.no",
                            FirstName = "Quinn",
                            LastName = "Roger",
                            PhoneNumber = "48679793",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 98,
                            Age = 21,
                            CourseId = 3,
                            Email = "dewalt94@uia.no",
                            FirstName = "Dewalt",
                            LastName = "George",
                            PhoneNumber = "48679794",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 99,
                            Age = 35,
                            CourseId = 1,
                            Email = "turco95@uia.no",
                            FirstName = "Turco",
                            LastName = "Nathan",
                            PhoneNumber = "48679795",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 100,
                            Age = 27,
                            CourseId = 1,
                            Email = "frick96@uia.no",
                            FirstName = "Frick",
                            LastName = "Caleb",
                            PhoneNumber = "48679796",
                            RegistrationDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IKT-205"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IKT-206"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IKT-203"
                        });
                });

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Course", "Courses")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
