// <auto-generated />
using System;
using BachCrud.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BachCrud.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240403165140_newDb")]
    partial class newDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            CourseId = 1,
                            Email = "mohamedzekaria@uia.no",
                            FirstName = "knaan",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            CourseId = 2,
                            Email = "moham@uia.no",
                            FirstName = "zeka",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            CourseId = 3,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            CourseId = 2,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Age = 38,
                            CourseId = 3,
                            Email = "ulrich1@uia.no",
                            FirstName = "Ulrich",
                            LastName = "Victor",
                            PhoneNumber = "4867971",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Age = 24,
                            CourseId = 2,
                            Email = "doran2@uia.no",
                            FirstName = "Doran",
                            LastName = "Edward",
                            PhoneNumber = "4867972",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Age = 35,
                            CourseId = 3,
                            Email = "casal3@uia.no",
                            FirstName = "Casal",
                            LastName = "Buford",
                            PhoneNumber = "4867973",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Age = 31,
                            CourseId = 1,
                            Email = "tandy4@uia.no",
                            FirstName = "Tandy",
                            LastName = "Roger",
                            PhoneNumber = "4867974",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Age = 25,
                            CourseId = 2,
                            Email = "uddin5@uia.no",
                            FirstName = "Uddin",
                            LastName = "Bunny",
                            PhoneNumber = "4867975",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Age = 42,
                            CourseId = 3,
                            Email = "kassing6@uia.no",
                            FirstName = "Kassing",
                            LastName = "Nathan",
                            PhoneNumber = "4867976",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Age = 42,
                            CourseId = 1,
                            Email = "weinstein7@uia.no",
                            FirstName = "Weinstein",
                            LastName = "Buffy",
                            PhoneNumber = "4867977",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Age = 35,
                            CourseId = 3,
                            Email = "tiernan8@uia.no",
                            FirstName = "Tiernan",
                            LastName = "Steve",
                            PhoneNumber = "4867978",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Age = 44,
                            CourseId = 1,
                            Email = "schuster9@uia.no",
                            FirstName = "Schuster",
                            LastName = "Aaron",
                            PhoneNumber = "4867979",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Age = 31,
                            CourseId = 2,
                            Email = "sweeney10@uia.no",
                            FirstName = "Sweeney",
                            LastName = "Calandra",
                            PhoneNumber = "48679710",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Age = 29,
                            CourseId = 2,
                            Email = "davis11@uia.no",
                            FirstName = "Davis",
                            LastName = "Hank",
                            PhoneNumber = "48679711",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Age = 24,
                            CourseId = 2,
                            Email = "sonderling12@uia.no",
                            FirstName = "Sonderling",
                            LastName = "Carl",
                            PhoneNumber = "48679712",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Age = 26,
                            CourseId = 1,
                            Email = "schwager13@uia.no",
                            FirstName = "Schwager",
                            LastName = "Nathan",
                            PhoneNumber = "48679713",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Age = 35,
                            CourseId = 3,
                            Email = "davidson14@uia.no",
                            FirstName = "Davidson",
                            LastName = "Larry",
                            PhoneNumber = "48679714",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Age = 23,
                            CourseId = 2,
                            Email = "allie15@uia.no",
                            FirstName = "Allie",
                            LastName = "Caitlin",
                            PhoneNumber = "48679715",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 20,
                            Age = 36,
                            CourseId = 3,
                            Email = "solberg16@uia.no",
                            FirstName = "Solberg",
                            LastName = "Monte",
                            PhoneNumber = "48679716",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 21,
                            Age = 22,
                            CourseId = 3,
                            Email = "johnson17@uia.no",
                            FirstName = "Johnson",
                            LastName = "Fred",
                            PhoneNumber = "48679717",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 22,
                            Age = 43,
                            CourseId = 1,
                            Email = "hoffman18@uia.no",
                            FirstName = "Hoffman",
                            LastName = "Caitlin",
                            PhoneNumber = "48679718",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 23,
                            Age = 22,
                            CourseId = 2,
                            Email = "mccormack19@uia.no",
                            FirstName = "McCormack",
                            LastName = "Buster",
                            PhoneNumber = "48679719",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 24,
                            Age = 32,
                            CourseId = 1,
                            Email = "nugent20@uia.no",
                            FirstName = "Nugent",
                            LastName = "Callie",
                            PhoneNumber = "48679720",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 25,
                            Age = 31,
                            CourseId = 2,
                            Email = "leisinger21@uia.no",
                            FirstName = "Leisinger",
                            LastName = "Callie",
                            PhoneNumber = "48679721",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 26,
                            Age = 40,
                            CourseId = 3,
                            Email = "soukup22@uia.no",
                            FirstName = "Soukup",
                            LastName = "David",
                            PhoneNumber = "48679722",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 27,
                            Age = 29,
                            CourseId = 1,
                            Email = "sonderling23@uia.no",
                            FirstName = "Sonderling",
                            LastName = "Edward",
                            PhoneNumber = "48679723",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 28,
                            Age = 28,
                            CourseId = 1,
                            Email = "alline24@uia.no",
                            FirstName = "Alline",
                            LastName = "Bulah",
                            PhoneNumber = "48679724",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 29,
                            Age = 39,
                            CourseId = 1,
                            Email = "knutson25@uia.no",
                            FirstName = "Knutson",
                            LastName = "Edward",
                            PhoneNumber = "48679725",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 30,
                            Age = 41,
                            CourseId = 2,
                            Email = "allene26@uia.no",
                            FirstName = "Allene",
                            LastName = "Burton",
                            PhoneNumber = "48679726",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 31,
                            Age = 23,
                            CourseId = 2,
                            Email = "allyson27@uia.no",
                            FirstName = "Allyson",
                            LastName = "Bula",
                            PhoneNumber = "48679727",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 32,
                            Age = 21,
                            CourseId = 3,
                            Email = "fietzer28@uia.no",
                            FirstName = "Fietzer",
                            LastName = "Buster",
                            PhoneNumber = "48679728",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 33,
                            Age = 23,
                            CourseId = 3,
                            Email = "schickowski29@uia.no",
                            FirstName = "Schickowski",
                            LastName = "Thomas",
                            PhoneNumber = "48679729",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 34,
                            Age = 20,
                            CourseId = 2,
                            Email = "sawyer30@uia.no",
                            FirstName = "Sawyer",
                            LastName = "Bunny",
                            PhoneNumber = "48679730",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 35,
                            Age = 22,
                            CourseId = 3,
                            Email = "hancock31@uia.no",
                            FirstName = "Hancock",
                            LastName = "Buster",
                            PhoneNumber = "48679731",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 36,
                            Age = 18,
                            CourseId = 1,
                            Email = "mccormack32@uia.no",
                            FirstName = "McCormack",
                            LastName = "Mark",
                            PhoneNumber = "48679732",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 37,
                            Age = 42,
                            CourseId = 1,
                            Email = "linde33@uia.no",
                            FirstName = "Linde",
                            LastName = "Buford",
                            PhoneNumber = "48679733",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 38,
                            Age = 38,
                            CourseId = 3,
                            Email = "dugan34@uia.no",
                            FirstName = "Dugan",
                            LastName = "Caleb",
                            PhoneNumber = "48679734",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 39,
                            Age = 39,
                            CourseId = 1,
                            Email = "fletcher35@uia.no",
                            FirstName = "Fletcher",
                            LastName = "Calista",
                            PhoneNumber = "48679735",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 40,
                            Age = 43,
                            CourseId = 2,
                            Email = "sellon36@uia.no",
                            FirstName = "Sellon",
                            LastName = "Otto",
                            PhoneNumber = "48679736",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 41,
                            Age = 25,
                            CourseId = 2,
                            Email = "ulrich37@uia.no",
                            FirstName = "Ulrich",
                            LastName = "Hank",
                            PhoneNumber = "48679737",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 42,
                            Age = 40,
                            CourseId = 1,
                            Email = "nelson38@uia.no",
                            FirstName = "Nelson",
                            LastName = "Nathan",
                            PhoneNumber = "48679738",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 43,
                            Age = 41,
                            CourseId = 2,
                            Email = "tiernan39@uia.no",
                            FirstName = "Tiernan",
                            LastName = "Victor",
                            PhoneNumber = "48679739",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 44,
                            Age = 32,
                            CourseId = 1,
                            Email = "alline40@uia.no",
                            FirstName = "Alline",
                            LastName = "Steve",
                            PhoneNumber = "48679740",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 45,
                            Age = 20,
                            CourseId = 3,
                            Email = "allene41@uia.no",
                            FirstName = "Allene",
                            LastName = "Calista",
                            PhoneNumber = "48679741",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 46,
                            Age = 36,
                            CourseId = 2,
                            Email = "trussel42@uia.no",
                            FirstName = "Trussel",
                            LastName = "Paul",
                            PhoneNumber = "48679742",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 47,
                            Age = 34,
                            CourseId = 1,
                            Email = "sandstrom43@uia.no",
                            FirstName = "Sandstrom",
                            LastName = "Paul",
                            PhoneNumber = "48679743",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 48,
                            Age = 36,
                            CourseId = 2,
                            Email = "tiernan44@uia.no",
                            FirstName = "Tiernan",
                            LastName = "Otto",
                            PhoneNumber = "48679744",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 49,
                            Age = 41,
                            CourseId = 1,
                            Email = "jurgenson45@uia.no",
                            FirstName = "Jurgenson",
                            LastName = "Steve",
                            PhoneNumber = "48679745",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 50,
                            Age = 21,
                            CourseId = 3,
                            Email = "delorenzo46@uia.no",
                            FirstName = "DeLorenzo",
                            LastName = "Buford",
                            PhoneNumber = "48679746",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 51,
                            Age = 44,
                            CourseId = 3,
                            Email = "lulloff47@uia.no",
                            FirstName = "Lulloff",
                            LastName = "Ben",
                            PhoneNumber = "48679747",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 52,
                            Age = 39,
                            CourseId = 1,
                            Email = "linde48@uia.no",
                            FirstName = "Linde",
                            LastName = "Caleb",
                            PhoneNumber = "48679748",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 53,
                            Age = 24,
                            CourseId = 2,
                            Email = "pettigrew49@uia.no",
                            FirstName = "Pettigrew",
                            LastName = "Burt",
                            PhoneNumber = "48679749",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 54,
                            Age = 18,
                            CourseId = 1,
                            Email = "ulrich50@uia.no",
                            FirstName = "Ulrich",
                            LastName = "Thomas",
                            PhoneNumber = "48679750",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 55,
                            Age = 38,
                            CourseId = 2,
                            Email = "allene51@uia.no",
                            FirstName = "Allene",
                            LastName = "Nathan",
                            PhoneNumber = "48679751",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 56,
                            Age = 38,
                            CourseId = 3,
                            Email = "allyson52@uia.no",
                            FirstName = "Allyson",
                            LastName = "Caleb",
                            PhoneNumber = "48679752",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 57,
                            Age = 39,
                            CourseId = 2,
                            Email = "napier53@uia.no",
                            FirstName = "Napier",
                            LastName = "Bulah",
                            PhoneNumber = "48679753",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 58,
                            Age = 44,
                            CourseId = 2,
                            Email = "leisinger54@uia.no",
                            FirstName = "Leisinger",
                            LastName = "Mark",
                            PhoneNumber = "48679754",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 59,
                            Age = 40,
                            CourseId = 2,
                            Email = "pettigrew55@uia.no",
                            FirstName = "Pettigrew",
                            LastName = "Steve",
                            PhoneNumber = "48679755",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 60,
                            Age = 19,
                            CourseId = 1,
                            Email = "trusela56@uia.no",
                            FirstName = "Trusela",
                            LastName = "Roger",
                            PhoneNumber = "48679756",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 61,
                            Age = 38,
                            CourseId = 1,
                            Email = "keller57@uia.no",
                            FirstName = "Keller",
                            LastName = "Carl",
                            PhoneNumber = "48679757",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 62,
                            Age = 44,
                            CourseId = 2,
                            Email = "valente58@uia.no",
                            FirstName = "Valente",
                            LastName = "Burton",
                            PhoneNumber = "48679758",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 63,
                            Age = 33,
                            CourseId = 1,
                            Email = "roberts59@uia.no",
                            FirstName = "Roberts",
                            LastName = "Calvin",
                            PhoneNumber = "48679759",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 64,
                            Age = 37,
                            CourseId = 2,
                            Email = "vail60@uia.no",
                            FirstName = "Vail",
                            LastName = "John",
                            PhoneNumber = "48679760",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 65,
                            Age = 22,
                            CourseId = 3,
                            Email = "allen61@uia.no",
                            FirstName = "Allen",
                            LastName = "Bula",
                            PhoneNumber = "48679761",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 66,
                            Age = 40,
                            CourseId = 3,
                            Email = "wagle62@uia.no",
                            FirstName = "Wagle",
                            LastName = "Burl",
                            PhoneNumber = "48679762",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 67,
                            Age = 25,
                            CourseId = 2,
                            Email = "vail63@uia.no",
                            FirstName = "Vail",
                            LastName = "Bulah",
                            PhoneNumber = "48679763",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 68,
                            Age = 30,
                            CourseId = 1,
                            Email = "keller64@uia.no",
                            FirstName = "Keller",
                            LastName = "Fred",
                            PhoneNumber = "48679764",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 69,
                            Age = 20,
                            CourseId = 3,
                            Email = "allena65@uia.no",
                            FirstName = "Allena",
                            LastName = "Mark",
                            PhoneNumber = "48679765",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 70,
                            Age = 42,
                            CourseId = 2,
                            Email = "fietzer66@uia.no",
                            FirstName = "Fietzer",
                            LastName = "Ike",
                            PhoneNumber = "48679766",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 71,
                            Age = 32,
                            CourseId = 1,
                            Email = "maki67@uia.no",
                            FirstName = "Maki",
                            LastName = "Jack",
                            PhoneNumber = "48679767",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 72,
                            Age = 34,
                            CourseId = 2,
                            Email = "johnsen68@uia.no",
                            FirstName = "Johnsen",
                            LastName = "Roger",
                            PhoneNumber = "48679768",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 73,
                            Age = 20,
                            CourseId = 1,
                            Email = "baxster69@uia.no",
                            FirstName = "Baxster",
                            LastName = "Mark",
                            PhoneNumber = "48679769",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 74,
                            Age = 37,
                            CourseId = 1,
                            Email = "pettigrew70@uia.no",
                            FirstName = "Pettigrew",
                            LastName = "Roger",
                            PhoneNumber = "48679770",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 75,
                            Age = 27,
                            CourseId = 3,
                            Email = "cataldi71@uia.no",
                            FirstName = "Cataldi",
                            LastName = "Camellia",
                            PhoneNumber = "48679771",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 76,
                            Age = 40,
                            CourseId = 1,
                            Email = "schlicht72@uia.no",
                            FirstName = "Schlicht",
                            LastName = "Nathan",
                            PhoneNumber = "48679772",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 77,
                            Age = 40,
                            CourseId = 3,
                            Email = "mccord73@uia.no",
                            FirstName = "Mccord",
                            LastName = "Ike",
                            PhoneNumber = "48679773",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 78,
                            Age = 27,
                            CourseId = 3,
                            Email = "cataldi74@uia.no",
                            FirstName = "Cataldi",
                            LastName = "Burl",
                            PhoneNumber = "48679774",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 79,
                            Age = 35,
                            CourseId = 1,
                            Email = "pak75@uia.no",
                            FirstName = "Pak",
                            LastName = "Burt",
                            PhoneNumber = "48679775",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 80,
                            Age = 36,
                            CourseId = 1,
                            Email = "schwager76@uia.no",
                            FirstName = "Schwager",
                            LastName = "Hal",
                            PhoneNumber = "48679776",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 81,
                            Age = 33,
                            CourseId = 2,
                            Email = "dinkins77@uia.no",
                            FirstName = "Dinkins",
                            LastName = "Tim",
                            PhoneNumber = "48679777",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 82,
                            Age = 31,
                            CourseId = 3,
                            Email = "eastman78@uia.no",
                            FirstName = "Eastman",
                            LastName = "Fred",
                            PhoneNumber = "48679778",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 83,
                            Age = 38,
                            CourseId = 1,
                            Email = "keller79@uia.no",
                            FirstName = "Keller",
                            LastName = "Buffy",
                            PhoneNumber = "48679779",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 84,
                            Age = 37,
                            CourseId = 3,
                            Email = "alix80@uia.no",
                            FirstName = "Alix",
                            LastName = "Joe",
                            PhoneNumber = "48679780",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 85,
                            Age = 24,
                            CourseId = 2,
                            Email = "solberg81@uia.no",
                            FirstName = "Solberg",
                            LastName = "Buffy",
                            PhoneNumber = "48679781",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 86,
                            Age = 43,
                            CourseId = 2,
                            Email = "uddin82@uia.no",
                            FirstName = "Uddin",
                            LastName = "Paul",
                            PhoneNumber = "48679782",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 87,
                            Age = 40,
                            CourseId = 1,
                            Email = "aliza83@uia.no",
                            FirstName = "Aliza",
                            LastName = "Byron",
                            PhoneNumber = "48679783",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 88,
                            Age = 43,
                            CourseId = 1,
                            Email = "bongard84@uia.no",
                            FirstName = "Bongard",
                            LastName = "Camelia",
                            PhoneNumber = "48679784",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 89,
                            Age = 31,
                            CourseId = 3,
                            Email = "tisler85@uia.no",
                            FirstName = "Tisler",
                            LastName = "Caitlin",
                            PhoneNumber = "48679785",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 90,
                            Age = 35,
                            CourseId = 3,
                            Email = "orwig86@uia.no",
                            FirstName = "Orwig",
                            LastName = "Mark",
                            PhoneNumber = "48679786",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 91,
                            Age = 43,
                            CourseId = 2,
                            Email = "caswell87@uia.no",
                            FirstName = "Caswell",
                            LastName = "Nathan",
                            PhoneNumber = "48679787",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 92,
                            Age = 36,
                            CourseId = 2,
                            Email = "lepage88@uia.no",
                            FirstName = "LePage",
                            LastName = "Burton",
                            PhoneNumber = "48679788",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 93,
                            Age = 42,
                            CourseId = 2,
                            Email = "nugent89@uia.no",
                            FirstName = "Nugent",
                            LastName = "Burt",
                            PhoneNumber = "48679789",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 94,
                            Age = 23,
                            CourseId = 2,
                            Email = "mcginnis90@uia.no",
                            FirstName = "McGinnis",
                            LastName = "Ben",
                            PhoneNumber = "48679790",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 95,
                            Age = 27,
                            CourseId = 2,
                            Email = "trussel91@uia.no",
                            FirstName = "Trussel",
                            LastName = "Ty",
                            PhoneNumber = "48679791",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 96,
                            Age = 39,
                            CourseId = 1,
                            Email = "tandy92@uia.no",
                            FirstName = "Tandy",
                            LastName = "Caitlyn",
                            PhoneNumber = "48679792",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 97,
                            Age = 36,
                            CourseId = 2,
                            Email = "christensen93@uia.no",
                            FirstName = "Christensen",
                            LastName = "Ben",
                            PhoneNumber = "48679793",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 98,
                            Age = 28,
                            CourseId = 1,
                            Email = "rogers94@uia.no",
                            FirstName = "Rogers",
                            LastName = "Otto",
                            PhoneNumber = "48679794",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 99,
                            Age = 31,
                            CourseId = 1,
                            Email = "ostrander95@uia.no",
                            FirstName = "Ostrander",
                            LastName = "Peter",
                            PhoneNumber = "48679795",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 100,
                            Age = 43,
                            CourseId = 1,
                            Email = "chambers96@uia.no",
                            FirstName = "Chambers",
                            LastName = "Monte",
                            PhoneNumber = "48679796",
                            RegistrationDate = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IKT-205"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IKT-206"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IKT-203"
                        });
                });

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Course", "Courses")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
