// <auto-generated />
using System;
using BachCrud.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BachCrud.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            CourseId = 1,
                            Email = "mohamedzekaria@uia.no",
                            FirstName = "knaan",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            CourseId = 2,
                            Email = "moham@uia.no",
                            FirstName = "zeka",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            CourseId = 3,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            CourseId = 2,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Age = 32,
                            CourseId = 1,
                            Email = "alix1@uia.no",
                            FirstName = "Alix",
                            LastName = "Buster",
                            PhoneNumber = "4867971",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Age = 40,
                            CourseId = 2,
                            Email = "allyson2@uia.no",
                            FirstName = "Allyson",
                            LastName = "Burma",
                            PhoneNumber = "4867972",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Age = 25,
                            CourseId = 2,
                            Email = "alisa3@uia.no",
                            FirstName = "Alisa",
                            LastName = "Burt",
                            PhoneNumber = "4867973",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Age = 24,
                            CourseId = 3,
                            Email = "alisa4@uia.no",
                            FirstName = "Alisa",
                            LastName = "Buster",
                            PhoneNumber = "4867974",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Age = 32,
                            CourseId = 2,
                            Email = "alita5@uia.no",
                            FirstName = "Alita",
                            LastName = "Calista",
                            PhoneNumber = "4867975",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Age = 41,
                            CourseId = 2,
                            Email = "alline6@uia.no",
                            FirstName = "Alline",
                            LastName = "Bulah",
                            PhoneNumber = "4867976",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Age = 35,
                            CourseId = 1,
                            Email = "allyn7@uia.no",
                            FirstName = "Allyn",
                            LastName = "Caitlyn",
                            PhoneNumber = "4867977",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Age = 37,
                            CourseId = 3,
                            Email = "allyson8@uia.no",
                            FirstName = "Allyson",
                            LastName = "Callie",
                            PhoneNumber = "4867978",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Age = 44,
                            CourseId = 3,
                            Email = "allan9@uia.no",
                            FirstName = "Allan",
                            LastName = "Buster",
                            PhoneNumber = "4867979",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Age = 41,
                            CourseId = 1,
                            Email = "alex 10@uia.no",
                            FirstName = "Alex ",
                            LastName = "Buffy",
                            PhoneNumber = "48679710",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Age = 33,
                            CourseId = 2,
                            Email = "allan11@uia.no",
                            FirstName = "Allan",
                            LastName = "Caitlin",
                            PhoneNumber = "48679711",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Age = 34,
                            CourseId = 3,
                            Email = "alisa12@uia.no",
                            FirstName = "Alisa",
                            LastName = "Buster",
                            PhoneNumber = "48679712",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Age = 31,
                            CourseId = 2,
                            Email = "alisia13@uia.no",
                            FirstName = "Alisia",
                            LastName = "Camellia",
                            PhoneNumber = "48679713",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Age = 40,
                            CourseId = 3,
                            Email = "alix14@uia.no",
                            FirstName = "Alix",
                            LastName = "Calista",
                            PhoneNumber = "48679714",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Age = 33,
                            CourseId = 2,
                            Email = "alla15@uia.no",
                            FirstName = "Alla",
                            LastName = "Burt",
                            PhoneNumber = "48679715",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 20,
                            Age = 36,
                            CourseId = 2,
                            Email = "alisia16@uia.no",
                            FirstName = "Alisia",
                            LastName = "Byron",
                            PhoneNumber = "48679716",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 21,
                            Age = 28,
                            CourseId = 2,
                            Email = "allene17@uia.no",
                            FirstName = "Allene",
                            LastName = "Burt",
                            PhoneNumber = "48679717",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 22,
                            Age = 36,
                            CourseId = 1,
                            Email = "allan18@uia.no",
                            FirstName = "Allan",
                            LastName = "Bulah",
                            PhoneNumber = "48679718",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 23,
                            Age = 38,
                            CourseId = 2,
                            Email = "alleen19@uia.no",
                            FirstName = "Alleen",
                            LastName = "Buffy",
                            PhoneNumber = "48679719",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 24,
                            Age = 30,
                            CourseId = 2,
                            Email = "allyson20@uia.no",
                            FirstName = "Allyson",
                            LastName = "Caitlyn",
                            PhoneNumber = "48679720",
                            RegistrationDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IKT-205"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IKT-206"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IKT-203"
                        });
                });

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Course", "Courses")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
