// <auto-generated />
using System;
using BachCrud.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BachCrud.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            CourseId = 1,
                            Email = "mohamedzekaria@uia.no",
                            FirstName = "knaan",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            CourseId = 2,
                            Email = "moham@uia.no",
                            FirstName = "zeka",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            CourseId = 3,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 4,
                            Age = 25,
                            CourseId = 2,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 5,
                            Age = 44,
                            CourseId = 2,
                            Email = "sweeney1@uia.no",
                            FirstName = "Sweeney",
                            LastName = "Buford",
                            PhoneNumber = "4867971",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 6,
                            Age = 33,
                            CourseId = 1,
                            Email = "root2@uia.no",
                            FirstName = "Root",
                            LastName = "John",
                            PhoneNumber = "4867972",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 7,
                            Age = 38,
                            CourseId = 3,
                            Email = "lepage3@uia.no",
                            FirstName = "LePage",
                            LastName = "George",
                            PhoneNumber = "4867973",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 8,
                            Age = 41,
                            CourseId = 3,
                            Email = "bateman4@uia.no",
                            FirstName = "Bateman",
                            LastName = "Dan",
                            PhoneNumber = "4867974",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 9,
                            Age = 27,
                            CourseId = 3,
                            Email = "severson5@uia.no",
                            FirstName = "Severson",
                            LastName = "Burt",
                            PhoneNumber = "4867975",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 10,
                            Age = 28,
                            CourseId = 2,
                            Email = "allie6@uia.no",
                            FirstName = "Allie",
                            LastName = "Byron",
                            PhoneNumber = "4867976",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 11,
                            Age = 43,
                            CourseId = 3,
                            Email = "ventotla7@uia.no",
                            FirstName = "Ventotla",
                            LastName = "Bunny",
                            PhoneNumber = "4867977",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 12,
                            Age = 30,
                            CourseId = 2,
                            Email = "vader8@uia.no",
                            FirstName = "Vader",
                            LastName = "Edward",
                            PhoneNumber = "4867978",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 13,
                            Age = 42,
                            CourseId = 1,
                            Email = "thompson9@uia.no",
                            FirstName = "Thompson",
                            LastName = "Matthew",
                            PhoneNumber = "4867979",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 14,
                            Age = 30,
                            CourseId = 1,
                            Email = "rogers10@uia.no",
                            FirstName = "Rogers",
                            LastName = "Thomas",
                            PhoneNumber = "48679710",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 15,
                            Age = 23,
                            CourseId = 2,
                            Email = "johnson11@uia.no",
                            FirstName = "Johnson",
                            LastName = "Camellia",
                            PhoneNumber = "48679711",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 16,
                            Age = 23,
                            CourseId = 1,
                            Email = "allena12@uia.no",
                            FirstName = "Allena",
                            LastName = "Camellia",
                            PhoneNumber = "48679712",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 17,
                            Age = 25,
                            CourseId = 3,
                            Email = "trusela13@uia.no",
                            FirstName = "Trusela",
                            LastName = "Caleb",
                            PhoneNumber = "48679713",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 18,
                            Age = 19,
                            CourseId = 2,
                            Email = "schickowski14@uia.no",
                            FirstName = "Schickowski",
                            LastName = "Jack",
                            PhoneNumber = "48679714",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 19,
                            Age = 20,
                            CourseId = 1,
                            Email = "reyes15@uia.no",
                            FirstName = "Reyes",
                            LastName = "Ty",
                            PhoneNumber = "48679715",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 20,
                            Age = 38,
                            CourseId = 1,
                            Email = "uflan16@uia.no",
                            FirstName = "Uflan",
                            LastName = "Calvin",
                            PhoneNumber = "48679716",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 21,
                            Age = 25,
                            CourseId = 3,
                            Email = "olson17@uia.no",
                            FirstName = "Olson",
                            LastName = "Buford",
                            PhoneNumber = "48679717",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 22,
                            Age = 34,
                            CourseId = 3,
                            Email = "vail18@uia.no",
                            FirstName = "Vail",
                            LastName = "Camelia",
                            PhoneNumber = "48679718",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 23,
                            Age = 21,
                            CourseId = 2,
                            Email = "van zandt19@uia.no",
                            FirstName = "Van Zandt",
                            LastName = "Camellia",
                            PhoneNumber = "48679719",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 24,
                            Age = 40,
                            CourseId = 3,
                            Email = "frick20@uia.no",
                            FirstName = "Frick",
                            LastName = "Calandra",
                            PhoneNumber = "48679720",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 25,
                            Age = 20,
                            CourseId = 2,
                            Email = "chapman21@uia.no",
                            FirstName = "Chapman",
                            LastName = "Calvin",
                            PhoneNumber = "48679721",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 26,
                            Age = 42,
                            CourseId = 1,
                            Email = "kalleg22@uia.no",
                            FirstName = "Kalleg",
                            LastName = "Frank",
                            PhoneNumber = "48679722",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 27,
                            Age = 40,
                            CourseId = 1,
                            Email = "sonderling23@uia.no",
                            FirstName = "Sonderling",
                            LastName = "Carl",
                            PhoneNumber = "48679723",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 28,
                            Age = 35,
                            CourseId = 3,
                            Email = "roberts24@uia.no",
                            FirstName = "Roberts",
                            LastName = "Calvin",
                            PhoneNumber = "48679724",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 29,
                            Age = 31,
                            CourseId = 3,
                            Email = "trebil25@uia.no",
                            FirstName = "Trebil",
                            LastName = "Camelia",
                            PhoneNumber = "48679725",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 30,
                            Age = 40,
                            CourseId = 1,
                            Email = "vader26@uia.no",
                            FirstName = "Vader",
                            LastName = "Callie",
                            PhoneNumber = "48679726",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 31,
                            Age = 25,
                            CourseId = 2,
                            Email = "yocum27@uia.no",
                            FirstName = "Yocum",
                            LastName = "Roger",
                            PhoneNumber = "48679727",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 32,
                            Age = 28,
                            CourseId = 1,
                            Email = "napier28@uia.no",
                            FirstName = "Napier",
                            LastName = "Tim",
                            PhoneNumber = "48679728",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 33,
                            Age = 43,
                            CourseId = 1,
                            Email = "johnsen29@uia.no",
                            FirstName = "Johnsen",
                            LastName = "Buford",
                            PhoneNumber = "48679729",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 34,
                            Age = 33,
                            CourseId = 3,
                            Email = "myers30@uia.no",
                            FirstName = "Myers",
                            LastName = "Matthew",
                            PhoneNumber = "48679730",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 35,
                            Age = 27,
                            CourseId = 3,
                            Email = "illingsworth31@uia.no",
                            FirstName = "Illingsworth",
                            LastName = "Camelia",
                            PhoneNumber = "48679731",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 36,
                            Age = 41,
                            CourseId = 1,
                            Email = "ferry32@uia.no",
                            FirstName = "Ferry",
                            LastName = "David",
                            PhoneNumber = "48679732",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 37,
                            Age = 19,
                            CourseId = 2,
                            Email = "ulrich33@uia.no",
                            FirstName = "Ulrich",
                            LastName = "Otto",
                            PhoneNumber = "48679733",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 38,
                            Age = 38,
                            CourseId = 3,
                            Email = "ventotla34@uia.no",
                            FirstName = "Ventotla",
                            LastName = "Buford",
                            PhoneNumber = "48679734",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 39,
                            Age = 42,
                            CourseId = 1,
                            Email = "dinkins35@uia.no",
                            FirstName = "Dinkins",
                            LastName = "Peter",
                            PhoneNumber = "48679735",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 40,
                            Age = 40,
                            CourseId = 1,
                            Email = "schiebel36@uia.no",
                            FirstName = "Schiebel",
                            LastName = "Calista",
                            PhoneNumber = "48679736",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 41,
                            Age = 26,
                            CourseId = 1,
                            Email = "allene37@uia.no",
                            FirstName = "Allene",
                            LastName = "Edward",
                            PhoneNumber = "48679737",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 42,
                            Age = 29,
                            CourseId = 1,
                            Email = "celedon38@uia.no",
                            FirstName = "Celedon",
                            LastName = "Nathan",
                            PhoneNumber = "48679738",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 43,
                            Age = 22,
                            CourseId = 2,
                            Email = "lulloff39@uia.no",
                            FirstName = "Lulloff",
                            LastName = "Caitlin",
                            PhoneNumber = "48679739",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 44,
                            Age = 19,
                            CourseId = 3,
                            Email = "napier40@uia.no",
                            FirstName = "Napier",
                            LastName = "Hal",
                            PhoneNumber = "48679740",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 45,
                            Age = 29,
                            CourseId = 1,
                            Email = "keller41@uia.no",
                            FirstName = "Keller",
                            LastName = "Otto",
                            PhoneNumber = "48679741",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 46,
                            Age = 42,
                            CourseId = 3,
                            Email = "vanderpoel42@uia.no",
                            FirstName = "Vanderpoel",
                            LastName = "Matthew",
                            PhoneNumber = "48679742",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 47,
                            Age = 19,
                            CourseId = 1,
                            Email = "turco43@uia.no",
                            FirstName = "Turco",
                            LastName = "Tim",
                            PhoneNumber = "48679743",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 48,
                            Age = 37,
                            CourseId = 3,
                            Email = "jones44@uia.no",
                            FirstName = "Jones",
                            LastName = "Buford",
                            PhoneNumber = "48679744",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 49,
                            Age = 35,
                            CourseId = 1,
                            Email = "chapman45@uia.no",
                            FirstName = "Chapman",
                            LastName = "Thomas",
                            PhoneNumber = "48679745",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 50,
                            Age = 28,
                            CourseId = 2,
                            Email = "dewalt46@uia.no",
                            FirstName = "Dewalt",
                            LastName = "Frank",
                            PhoneNumber = "48679746",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 51,
                            Age = 39,
                            CourseId = 1,
                            Email = "anderson47@uia.no",
                            FirstName = "Anderson",
                            LastName = "Calista",
                            PhoneNumber = "48679747",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 52,
                            Age = 34,
                            CourseId = 1,
                            Email = "lulloff48@uia.no",
                            FirstName = "Lulloff",
                            LastName = "Hank",
                            PhoneNumber = "48679748",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 53,
                            Age = 36,
                            CourseId = 3,
                            Email = "trebil49@uia.no",
                            FirstName = "Trebil",
                            LastName = "Caitlyn",
                            PhoneNumber = "48679749",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 54,
                            Age = 33,
                            CourseId = 2,
                            Email = "jones50@uia.no",
                            FirstName = "Jones",
                            LastName = "Thomas",
                            PhoneNumber = "48679750",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 55,
                            Age = 39,
                            CourseId = 2,
                            Email = "ashwoon51@uia.no",
                            FirstName = "Ashwoon",
                            LastName = "Jack",
                            PhoneNumber = "48679751",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 56,
                            Age = 26,
                            CourseId = 2,
                            Email = "delorenzo52@uia.no",
                            FirstName = "DeLorenzo",
                            LastName = "Matthew",
                            PhoneNumber = "48679752",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 57,
                            Age = 18,
                            CourseId = 2,
                            Email = "dewalt53@uia.no",
                            FirstName = "Dewalt",
                            LastName = "Bunny",
                            PhoneNumber = "48679753",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 58,
                            Age = 37,
                            CourseId = 3,
                            Email = "ashwoon54@uia.no",
                            FirstName = "Ashwoon",
                            LastName = "Calvin",
                            PhoneNumber = "48679754",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 59,
                            Age = 36,
                            CourseId = 3,
                            Email = "alla55@uia.no",
                            FirstName = "Alla",
                            LastName = "Roger",
                            PhoneNumber = "48679755",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 60,
                            Age = 21,
                            CourseId = 2,
                            Email = "olson56@uia.no",
                            FirstName = "Olson",
                            LastName = "Buffy",
                            PhoneNumber = "48679756",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 61,
                            Age = 29,
                            CourseId = 1,
                            Email = "cataldi57@uia.no",
                            FirstName = "Cataldi",
                            LastName = "Calvin",
                            PhoneNumber = "48679757",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 62,
                            Age = 43,
                            CourseId = 1,
                            Email = "orwig58@uia.no",
                            FirstName = "Orwig",
                            LastName = "Camelia",
                            PhoneNumber = "48679758",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 63,
                            Age = 18,
                            CourseId = 2,
                            Email = "illingsworth59@uia.no",
                            FirstName = "Illingsworth",
                            LastName = "Monte",
                            PhoneNumber = "48679759",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 64,
                            Age = 32,
                            CourseId = 3,
                            Email = "reyes60@uia.no",
                            FirstName = "Reyes",
                            LastName = "Bunny",
                            PhoneNumber = "48679760",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 65,
                            Age = 27,
                            CourseId = 2,
                            Email = "paiser61@uia.no",
                            FirstName = "Paiser",
                            LastName = "Burl",
                            PhoneNumber = "48679761",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 66,
                            Age = 26,
                            CourseId = 2,
                            Email = "allena62@uia.no",
                            FirstName = "Allena",
                            LastName = "Buford",
                            PhoneNumber = "48679762",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 67,
                            Age = 33,
                            CourseId = 3,
                            Email = "ebner63@uia.no",
                            FirstName = "Ebner",
                            LastName = "Ty",
                            PhoneNumber = "48679763",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 68,
                            Age = 28,
                            CourseId = 2,
                            Email = "vogal64@uia.no",
                            FirstName = "Vogal",
                            LastName = "Ty",
                            PhoneNumber = "48679764",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 69,
                            Age = 44,
                            CourseId = 1,
                            Email = "paiser65@uia.no",
                            FirstName = "Paiser",
                            LastName = "Ty",
                            PhoneNumber = "48679765",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 70,
                            Age = 18,
                            CourseId = 3,
                            Email = "reamer66@uia.no",
                            FirstName = "Reamer",
                            LastName = "Ty",
                            PhoneNumber = "48679766",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 71,
                            Age = 30,
                            CourseId = 2,
                            Email = "alix67@uia.no",
                            FirstName = "Alix",
                            LastName = "Aaron",
                            PhoneNumber = "48679767",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 72,
                            Age = 33,
                            CourseId = 1,
                            Email = "ziegler68@uia.no",
                            FirstName = "Ziegler",
                            LastName = "Burt",
                            PhoneNumber = "48679768",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 73,
                            Age = 28,
                            CourseId = 3,
                            Email = "mccormack69@uia.no",
                            FirstName = "McCormack",
                            LastName = "George",
                            PhoneNumber = "48679769",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 74,
                            Age = 27,
                            CourseId = 1,
                            Email = "allyson70@uia.no",
                            FirstName = "Allyson",
                            LastName = "Buster",
                            PhoneNumber = "48679770",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 75,
                            Age = 27,
                            CourseId = 2,
                            Email = "dugan71@uia.no",
                            FirstName = "Dugan",
                            LastName = "Jack",
                            PhoneNumber = "48679771",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 76,
                            Age = 24,
                            CourseId = 1,
                            Email = "nugent72@uia.no",
                            FirstName = "Nugent",
                            LastName = "Camellia",
                            PhoneNumber = "48679772",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 77,
                            Age = 35,
                            CourseId = 2,
                            Email = "rice73@uia.no",
                            FirstName = "Rice",
                            LastName = "Mark",
                            PhoneNumber = "48679773",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 78,
                            Age = 34,
                            CourseId = 2,
                            Email = "johnsen74@uia.no",
                            FirstName = "Johnsen",
                            LastName = "Bula",
                            PhoneNumber = "48679774",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 79,
                            Age = 27,
                            CourseId = 2,
                            Email = "delorenzo75@uia.no",
                            FirstName = "DeLorenzo",
                            LastName = "Joe",
                            PhoneNumber = "48679775",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 80,
                            Age = 39,
                            CourseId = 1,
                            Email = "darnell76@uia.no",
                            FirstName = "Darnell",
                            LastName = "Callie",
                            PhoneNumber = "48679776",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 81,
                            Age = 34,
                            CourseId = 2,
                            Email = "mcginnis77@uia.no",
                            FirstName = "McGinnis",
                            LastName = "John",
                            PhoneNumber = "48679777",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 82,
                            Age = 40,
                            CourseId = 2,
                            Email = "jagtap78@uia.no",
                            FirstName = "Jagtap",
                            LastName = "Dan",
                            PhoneNumber = "48679778",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 83,
                            Age = 23,
                            CourseId = 1,
                            Email = "mills79@uia.no",
                            FirstName = "Mills",
                            LastName = "Joe",
                            PhoneNumber = "48679779",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 84,
                            Age = 42,
                            CourseId = 1,
                            Email = "zeller80@uia.no",
                            FirstName = "Zeller",
                            LastName = "Ty",
                            PhoneNumber = "48679780",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 85,
                            Age = 22,
                            CourseId = 1,
                            Email = "allison81@uia.no",
                            FirstName = "Allison",
                            LastName = "Jack",
                            PhoneNumber = "48679781",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 86,
                            Age = 40,
                            CourseId = 1,
                            Email = "uflan82@uia.no",
                            FirstName = "Uflan",
                            LastName = "Callie",
                            PhoneNumber = "48679782",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 87,
                            Age = 37,
                            CourseId = 1,
                            Email = "lawless83@uia.no",
                            FirstName = "Lawless",
                            LastName = "Camelia",
                            PhoneNumber = "48679783",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 88,
                            Age = 35,
                            CourseId = 2,
                            Email = "weinstein84@uia.no",
                            FirstName = "Weinstein",
                            LastName = "Bunny",
                            PhoneNumber = "48679784",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 89,
                            Age = 28,
                            CourseId = 3,
                            Email = "maki85@uia.no",
                            FirstName = "Maki",
                            LastName = "Bunny",
                            PhoneNumber = "48679785",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 90,
                            Age = 29,
                            CourseId = 1,
                            Email = "alisain86@uia.no",
                            FirstName = "Alisain",
                            LastName = "Roger",
                            PhoneNumber = "48679786",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 91,
                            Age = 37,
                            CourseId = 1,
                            Email = "vogal87@uia.no",
                            FirstName = "Vogal",
                            LastName = "Paul",
                            PhoneNumber = "48679787",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 92,
                            Age = 18,
                            CourseId = 1,
                            Email = "allen88@uia.no",
                            FirstName = "Allen",
                            LastName = "George",
                            PhoneNumber = "48679788",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 93,
                            Age = 42,
                            CourseId = 3,
                            Email = "cannon89@uia.no",
                            FirstName = "Cannon",
                            LastName = "Paul",
                            PhoneNumber = "48679789",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 94,
                            Age = 42,
                            CourseId = 2,
                            Email = "alix90@uia.no",
                            FirstName = "Alix",
                            LastName = "Ben",
                            PhoneNumber = "48679790",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 95,
                            Age = 35,
                            CourseId = 1,
                            Email = "kalleg91@uia.no",
                            FirstName = "Kalleg",
                            LastName = "Byron",
                            PhoneNumber = "48679791",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 96,
                            Age = 41,
                            CourseId = 2,
                            Email = "ferry92@uia.no",
                            FirstName = "Ferry",
                            LastName = "Calandra",
                            PhoneNumber = "48679792",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 97,
                            Age = 40,
                            CourseId = 1,
                            Email = "allyn93@uia.no",
                            FirstName = "Allyn",
                            LastName = "Ike",
                            PhoneNumber = "48679793",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 98,
                            Age = 22,
                            CourseId = 2,
                            Email = "pettigrew94@uia.no",
                            FirstName = "Pettigrew",
                            LastName = "Dan",
                            PhoneNumber = "48679794",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 99,
                            Age = 30,
                            CourseId = 2,
                            Email = "maki95@uia.no",
                            FirstName = "Maki",
                            LastName = "Camellia",
                            PhoneNumber = "48679795",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 100,
                            Age = 38,
                            CourseId = 2,
                            Email = "dugan96@uia.no",
                            FirstName = "Dugan",
                            LastName = "Buford",
                            PhoneNumber = "48679796",
                            RegistrationDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IKT-205"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IKT-206"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IKT-203"
                        });
                });

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Course", "Courses")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
