// <auto-generated />
using System;
using BachCrud.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BachCrud.Server.Migrations
{
    [DbContext(typeof(ApplictionDbContext))]
    partial class ApplictionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 23,
                            CourseId = 1,
                            Email = "mohamedzekaria@uia.no",
                            FirstName = "knaan",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 2,
                            Age = 24,
                            CourseId = 2,
                            Email = "moham@uia.no",
                            FirstName = "zeka",
                            LastName = "Mohamed",
                            PhoneNumber = "0045845858",
                            RegistrationDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 3,
                            Age = 25,
                            CourseId = 3,
                            Email = "mo@uia.no",
                            FirstName = "Mo",
                            LastName = "Ali",
                            PhoneNumber = "004348",
                            RegistrationDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "IKT-205"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IKT-206"
                        },
                        new
                        {
                            Id = 3,
                            Name = "IKT-203"
                        });
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "HR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT"
                        });
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireData")
                        .HasColumnType("datetime2");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FullName = "knaan Mohamed",
                            HireData = new DateTime(2024, 2, 2, 14, 27, 49, 676, DateTimeKind.Local).AddTicks(6720),
                            Salary = 98
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            FullName = "knaan Mohamed",
                            HireData = new DateTime(2024, 2, 2, 14, 27, 49, 676, DateTimeKind.Local).AddTicks(6790),
                            Salary = 98
                        });
                });

            modelBuilder.Entity("BachCrud.Server.Models.Student", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Course", "Courses")
                        .WithMany("Students")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Courses");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Employee", b =>
                {
                    b.HasOne("BlazorCrud.Server.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Course", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("BlazorCrud.Server.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
