name: Blazor Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.101' # specify your dotnet version

    - name: Restore dependencies for BlazorTests
      run: dotnet restore ./BlazorTests/BlazorTests.csproj

    - name: Run BlazorTests
      run: dotnet test ./BlazorTests/BlazorTests.csproj --no-restore --verbosity normal
