# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - bachBlazorClient

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  test: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with: 
          dotnet-version: '8.0.101'
      - name: Install required workloads
        run: dotnet workload install wasm-tools
      - name: Restore dependencies for BlazorTests 
        run:  dotnet restore bachCrudApp/BlazorTests/BlazorTests.csproj
      - name: Run Blazor Tests 
        run: dotnet test bachCrudApp/BlazorTests/BlazorTests.csproj --no-restore --verbosity normal
  
  build:
    runs-on: windows-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.101'
          include-prerelease: true
      - name: Install wasm-tools workload
        run: dotnet workload install wasm-tools

      - name: Build with dotnet
        run: dotnet build --configuration Release bachCrudApp/BachCrud.sln

      - name: dotnet publish
        run: dotnet publish bachCrudApp/BachCrud.Client/BachCrud.Client.csproj -c Release -o ./myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ./myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0D25E75B939241F8AD4E08634AFB1F15 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60244365202F48E5813419F140E390E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0BB98BFE01E44B00894D830AD1A136ED }}


      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bach-Blazor-client'
          slot-name: 'Production'
          package: .
          
